# Generated by Django 5.1.4 on 2025-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_emailverificationotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationotp',
            name='otp',
            field=models.PositiveIntegerField(),
        ),
    ]
