# Generated by Django 5.1.4 on 2025-01-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_emailverificationotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
