# Generated by Django 5.1.4 on 2024-12-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_favicon_alter_company_logo'),
        ('registration', '0002_registrationsubtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_required', models.CharField(blank=True, max_length=100, null=True)),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype')),
            ],
            options={
                'db_table': 'registration_detail',
                'ordering': ['-created'],
            },
        ),
    ]
