# Generated by Django 5.1.4 on 2025-01-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registrationdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
