# Generated by Django 5.1.4 on 2025-02-03 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='registration_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
        ),
    ]
