# Generated by Django 5.1.4 on 2025-03-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_multipagebulletpoint_multipagefaq_multipagefeature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagebulletpoint',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagefaq',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagefeature',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontalbullet',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontaltab',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagetable',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagetabledata',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagetag',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipagetimeline',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipageverticalbullet',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='multipageverticaltab',
            name='registration',
        ),
        migrations.AddField(
            model_name='multipage',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagebulletpoint',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagefaq',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagefeature',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagehorizontalbullet',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagehorizontaltab',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagetable',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagetabledata',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagetag',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagetimeline',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipageverticalbullet',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipageverticaltab',
            name='registration_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
    ]
