# Generated by Django 5.1.4 on 2025-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_bulletpoint_feature_horizontalbullet_horizontaltab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetailpage',
            name='meta_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
