# Generated by Django 5.1.4 on 2025-03-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_multipage_url_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='meta_tags',
        ),
        migrations.RemoveField(
            model_name='registrationdetailpage',
            name='meta_tags',
        ),
    ]
