# Generated by Django 5.1.4 on 2025-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_multipage_meta_tags_registrationdetailpage_meta_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetailpage',
            name='hide_support_languages',
            field=models.BooleanField(default=False),
        ),
    ]
