# Generated by Django 5.1.4 on 2025-05-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_company_created_company_updated'),
        ('registration', '0017_registrationdetailpage_hide_support_languages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationDetail',
            new_name='Registration',
        ),
    ]
