# Generated by Django 5.1.4 on 2025-05-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_rename_registrationdetail_registration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registrations',
        ),
    ]
