# Generated by Django 5.1.4 on 2025-05-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_registration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='hide_support_languages',
            field=models.BooleanField(default=False),
        ),
    ]
