# Generated by Django 5.1.4 on 2025-05-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_multipage_hide_support_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipagefaq',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
