# Generated by Django 5.1.4 on 2025-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0029_rename_pincode_uniqueplace_pincodes'),
        ('registration', '0021_multipagefaq_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='available_states',
            field=models.ManyToManyField(to='locations.uniquestate'),
        ),
        migrations.AddField(
            model_name='multipage',
            name='course_region',
            field=models.CharField(default='all', max_length=250),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='timelines',
            field=models.ManyToManyField(related_name='registration_multipage_states', to='registration.multipagetimeline'),
        ),
    ]
