# Generated by Django 5.1.4 on 2025-05-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_multipage_available_states_multipage_course_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipage',
            old_name='course_region',
            new_name='registration_region',
        ),
    ]
