# Generated by Django 5.1.4 on 2025-05-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_rename_course_region_multipage_registration_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagebulletpoint',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagefaq',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagefeature',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontalbullet',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontaltab',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagetable',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagetabledata',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagetag',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipagetimeline',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipageverticalbullet',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='multipageverticaltab',
            name='registration_sub_type',
        ),
    ]
