# Generated by Django 5.1.4 on 2025-05-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_multipage_title_multipagebulletpoint_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
        ),
    ]
