# Generated by Django 5.1.4 on 2025-05-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_multipage_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipage',
            name='registration',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
            preserve_default=False,
        ),
    ]
