# Generated by Django 5.1.4 on 2025-07-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_alter_multipage_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
    ]
