# Generated by Django 5.1.4 on 2025-07-14 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_metatag_meta_description_metatag_meta_title'),
        ('company', '0029_banner'),
        ('locations', '0040_omancoordinates_omanlocationdata'),
        ('registration', '0028_remove_enquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='available_states',
            field=models.ManyToManyField(related_name='registration_multipages', to='locations.uniquestate'),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_multipages', to='company.company'),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='meta_tags',
            field=models.ManyToManyField(related_name='registration_multipages', to='base.metatag'),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipages', to='registration.registrationsubtype'),
        ),
    ]
