# Generated by Django 5.1.4 on 2025-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_multipage_sub_title_alter_multipage_available_states_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='slider_registrations',
            field=models.ManyToManyField(to='registration.registrationdetailpage'),
        ),
    ]
