# Generated by Django 5.1.4 on 2025-08-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_multipage_slider_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='home_footer_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
