# Generated by Django 5.1.4 on 2025-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_multipage_home_footer_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='registration_sub_types/'),
        ),
    ]
