# Generated by Django 5.1.4 on 2025-08-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_registrationsubtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_sub_types', to='registration.registrationtype'),
        ),
    ]
