# Generated by Django 5.1.4 on 2025-08-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_alter_registrationsubtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='registrationdetailpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='hide_tags',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='tag_title',
        ),
        migrations.RemoveField(
            model_name='registrationdetailpage',
            name='hide_tags',
        ),
        migrations.RemoveField(
            model_name='registrationdetailpage',
            name='tag_title',
        ),
        migrations.DeleteModel(
            name='MultiPageTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
