# Generated by Django 5.1.4 on 2025-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_remove_multipage_tags_remove_tag_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetailpage',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
