# Generated by Django 5.1.4 on 2025-08-18 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_registrationdetailpage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetailpage',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='registrationdetailpage',
            name='title',
        ),
        migrations.AddField(
            model_name='registration',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationtype'),
        ),
        migrations.AddField(
            model_name='registrationdetailpage',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
    ]
