# Generated by Django 5.1.4 on 2025-08-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_remove_registrationdetailpage_registration_sub_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='type',
            new_name='registration_type',
        ),
    ]
