# Generated by Django 5.1.4 on 2025-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_rename_type_registration_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
