# Generated by Django 5.1.4 on 2025-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_alter_registration_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsubtype',
            name='image',
        ),
        migrations.AddField(
            model_name='registrationdetailpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/'),
        ),
    ]
