# Generated by Django 5.1.4 on 2025-08-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_remove_registrationsubtype_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetailpage',
            name='image',
        ),
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/'),
        ),
    ]
