# Generated by Django 5.1.4 on 2025-08-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_remove_registrationdetailpage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='image',
        ),
    ]
