# Generated by Django 5.1.4 on 2025-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_remove_registration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/'),
        ),
    ]
