# Generated by Django 5.1.4 on 2025-08-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_registration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletpoint',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='horizontalbullet',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='horizontaltab',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='table',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='tabledata',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='verticalbullet',
            name='registration_sub_type',
        ),
        migrations.RemoveField(
            model_name='verticaltab',
            name='registration_sub_type',
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horizontalbullet',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horizontaltab',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabledata',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verticalbullet',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verticaltab',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
    ]
