# Generated by Django 5.1.4 on 2025-08-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_remove_bulletpoint_registration_sub_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='registration_sub_type',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.registrationtype'),
        ),
    ]
