# Generated by Django 5.1.4 on 2025-08-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_remove_enquiry_registration_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.registrationsubtype'),
        ),
    ]
