# Generated by Django 5.1.4 on 2025-08-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_alter_registration_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='registration',
        ),
    ]
