# Generated by Django 5.1.4 on 2025-08-20 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_multipage_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='registration_sub_type',
        ),
        migrations.AddField(
            model_name='faq',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
            preserve_default=False,
        ),
    ]
