# Generated by Django 5.1.4 on 2025-08-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_remove_faq_registration_sub_type_faq_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='registration.registration'),
        ),
    ]
