# Generated by Django 5.1.4 on 2025-08-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('registration', '0049_alter_faq_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='company.company'),
        ),
    ]
