# Generated by Django 5.1.4 on 2025-08-20 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('registration', '0050_alter_registration_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='registration',
        ),
        migrations.AlterField(
            model_name='multipagehorizontalbullet',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hori_verticle_tabs', to='company.company'),
        ),
        migrations.AlterField(
            model_name='multipagetable',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_tables', to='company.company'),
        ),
        migrations.AlterField(
            model_name='multipageverticaltab',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_vertical_tabs', to='company.company'),
        ),
    ]
