# Generated by Django 5.1.4 on 2025-08-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_remove_multipage_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multipages', to='registration.registration'),
            preserve_default=False,
        ),
    ]
