# Generated by Django 5.1.4 on 2025-08-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_multipage_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipage',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
