# Generated by Django 5.1.4 on 2025-08-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_alter_multipage_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='registration.registration'),
        ),
    ]
