# Generated by Django 5.1.4 on 2025-08-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('registration', '0054_alter_registrationdetailpage_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='company.company'),
        ),
        migrations.AlterField(
            model_name='registrationdetailpage',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
    ]
