# Generated by Django 5.1.4 on 2025-01-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_favicon_alter_company_logo'),
        ('custom_pages', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('last_updated', models.DateField(blank=True, null=True, verbose_name='Last Updated')),
                ('information_collection', models.TextField(blank=True, null=True, verbose_name='Information Collection')),
                ('use_of_information', models.TextField(blank=True, null=True, verbose_name='Use of Information')),
                ('information_sharing', models.TextField(blank=True, null=True, verbose_name='Information Sharing')),
                ('user_rights', models.TextField(blank=True, null=True, verbose_name='User Rights')),
                ('cookies_tracking', models.TextField(blank=True, null=True, verbose_name='Cookies and Tracking')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('slug', models.SlugField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'privacy_policies',
                'ordering': ['company__name'],
            },
        ),
    ]
