# Generated by Django 5.1.4 on 2025-01-09 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_favicon_alter_company_logo'),
        ('custom_pages', '0004_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Full text of the Terms and Conditions.')),
                ('version', models.CharField(help_text='Version number of the Terms and Conditions.', max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='The date when these terms became effective.')),
                ('is_active', models.BooleanField(default=False, help_text='Indicates if this version is currently active.')),
                ('slug', models.SlugField(blank=True, help_text='The slug of the record', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions',
                'ordering': ['-effective_date'],
            },
        ),
    ]
