# Generated by Django 5.1.4 on 2025-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0005_termsandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='intro_text',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='intro',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
