# Generated by Django 5.1.4 on 2025-01-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0006_remove_aboutus_intro_text_aboutus_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='city',
            new_name='place',
        ),
    ]
