# Generated by Django 5.1.4 on 2025-01-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0007_rename_city_contactus_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
