# Generated by Django 5.1.4 on 2025-01-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0009_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='cookies_tracking',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='information_collection',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='information_sharing',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='use_of_information',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='user_rights',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(default='Content', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
