# Generated by Django 5.1.4 on 2025-01-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0010_remove_privacypolicy_cookies_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
