# Generated by Django 5.1.4 on 2025-01-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0011_privacypolicy_support_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='history',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='team_info',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='vision',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content',
            field=models.TextField(default='About Us', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
