# Generated by Django 5.1.4 on 2025-01-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_favicon_alter_company_logo'),
        ('custom_pages', '0013_shippinganddeliverypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationAndRefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.SlugField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'cancellation_and_refund_policy',
                'ordering': ['company__name'],
            },
        ),
    ]
