# Generated by Django 5.1.4 on 2025-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0015_alter_aboutus_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cancellationandrefundpolicy',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shippinganddeliverypolicy',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
