# Generated by Django 5.1.4 on 2025-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0016_alter_aboutus_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='summary',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
