# Generated by Django 5.1.4 on 2025-07-25 12:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0017_faq_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='summary',
            new_name='short_answer',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
