# Generated by Django 5.1.4 on 2025-08-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_alter_testimonial_company'),
        ('custom_pages', '0018_rename_summary_faq_short_answer_alter_faq_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermsAndConditions',
            new_name='TermsAndCondition',
        ),
    ]
