# Generated by Django 5.1.4 on 2025-08-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0023_alter_cancellationandrefundpolicy_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='facebook',
            new_name='web',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='x',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='youtube',
        ),
        migrations.AddField(
            model_name='contactus',
            name='tel',
            field=models.CharField(default='9876543210', max_length=20),
            preserve_default=False,
        ),
    ]
