# Generated by Django 5.1.4 on 2025-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0024_rename_phone_contactus_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
