# Generated by Django 5.1.4 on 2025-08-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('custom_pages', '0026_alter_contactus_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.company'),
        ),
    ]
