# Generated by Django 5.1.2 on 2024-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.CharField(max_length=150)),
                ('region_name', models.CharField(max_length=150)),
                ('division_name', models.CharField(max_length=150)),
                ('office_name', models.CharField(max_length=150)),
                ('pincode', models.PositiveIntegerField()),
                ('office_type', models.CharField(max_length=150)),
                ('delivery', models.BooleanField(default=False)),
                ('district', models.CharField(max_length=150)),
                ('state_name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'post_offices',
                'ordering': ['pincode'],
            },
        ),
    ]
