# Generated by Django 5.1.2 on 2024-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_postoffice_circle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('osm_id', models.CharField(max_length=255, unique=True)),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Stations',
            },
        ),
    ]
