# Generated by Django 5.1.4 on 2024-12-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_policestation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ifsc', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=150)),
                ('center', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('iso3166', models.CharField(max_length=50)),
                ('micr', models.CharField(max_length=50)),
                ('swift', models.CharField(max_length=50)),
                ('imps', models.BooleanField(default=False)),
                ('rtgs', models.BooleanField(default=False)),
                ('neft', models.BooleanField(default=False)),
                ('upi', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'banks',
                'ordering': ['ifsc'],
            },
        ),
    ]
