# Generated by Django 5.1.4 on 2024-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_bank_latitude_bank_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='swift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
