# Generated by Django 5.1.4 on 2024-12-07 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_touristattraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristattraction',
            old_name='name_punjab',
            new_name='name_punjabi',
        ),
        migrations.RenameField(
            model_name='touristattraction',
            old_name='steet',
            new_name='street',
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9d86e7d9-4eca-43a3-9534-302011419ea6')),
        ),
    ]
