# Generated by Django 5.1.4 on 2024-12-07 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_rename_name_punjab_touristattraction_name_punjabi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touristattraction',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('463e1928-dbf0-4ba6-8500-64dcecdb3af9')),
        ),
        migrations.AlterModelTable(
            name='touristattraction',
            table='attractions',
        ),
    ]
