# Generated by Django 5.1.4 on 2024-12-07 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_alter_touristattraction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b43ee321-ba94-4821-9926-3ce9eabfd710')),
        ),
    ]
