# Generated by Django 5.1.4 on 2024-12-07 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_alter_touristattraction_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ddda36a2-43d3-4761-8d6f-6bcddfd0f31c')),
        ),
    ]
