# Generated by Django 5.1.4 on 2024-12-07 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristattraction',
            name='name_english',
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('976fcb77-a87a-42ca-91ab-af1497f31908')),
        ),
    ]
