# Generated by Django 5.1.4 on 2024-12-10 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_court_designation_court_name_assamese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('07889a6b-e234-42ec-9431-0b762f4af50c')),
        ),
        migrations.AlterModelTable(
            name='court',
            table='courts',
        ),
    ]
