# Generated by Django 5.1.4 on 2024-12-10 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_alter_touristattraction_slug_alter_court_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policestation',
            old_name='address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='policestation',
            old_name='address_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='policestation',
            old_name='address_postcode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='policestation',
            old_name='building',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='policestation',
            old_name='government',
            new_name='street',
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9b367eea-b190-4e46-b93e-0b21718b7cb6')),
        ),
    ]
