# Generated by Django 5.1.4 on 2025-01-03 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_remove_policestation_opening_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('34adeb6e-5f09-435a-97ff-dea802eca9ae')),
        ),
    ]
