# Generated by Django 5.1.4 on 2025-01-13 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0027_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a56e99a1-e948-4c9d-ab3d-92aba482bcef')),
        ),
    ]
