# Generated by Django 5.1.4 on 2025-01-14 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('aa27a768-9bce-432b-98ec-da9d51fdfc61')),
        ),
    ]
