# Generated by Django 5.1.4 on 2025-01-14 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0030_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ef5f05d5-ea91-447c-81d8-50e778c66778')),
        ),
    ]
