# Generated by Django 5.1.4 on 2025-01-14 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0031_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e7bceb18-af7e-4e81-91ff-c6615cb95b3e')),
        ),
    ]
