# Generated by Django 5.1.4 on 2025-01-14 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0032_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a8f68126-fbe9-4f6d-8487-844a809e5167')),
        ),
    ]
