# Generated by Django 5.1.4 on 2025-01-15 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0033_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('a1620a95-b8c8-4291-816e-315a3ea8f0d9')),
        ),
    ]
