# Generated by Django 5.1.4 on 2025-01-15 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0035_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0e879d45-ee74-4c40-9eee-ab8b6673dc37')),
        ),
    ]
