# Generated by Django 5.1.4 on 2025-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0037_alter_touristattraction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
