# Generated by Django 5.1.4 on 2025-06-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0039_destination'),
        ('locations', '0029_rename_pincode_uniqueplace_pincodes'),
        ('registration', '0027_alter_multipage_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CscCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csc_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('location', models.TextField()),
                ('zipcode', models.CharField(max_length=15)),
                ('landmark_or_building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='csc_center_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniquedistrict')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniqueplace')),
                ('services', models.ManyToManyField(to='registration.registrationsubtype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniquestate')),
            ],
        ),
    ]
