# Generated by Django 5.1.4 on 2025-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0040_csccenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
