# Generated by Django 5.1.4 on 2025-06-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0041_alter_csccenter_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csccenter',
            old_name='services',
            new_name='registrations',
        ),
    ]
