# Generated by Django 5.1.4 on 2025-06-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0042_rename_services_csccenter_registrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csccenter',
            old_name='csc_reg_no',
            new_name='csc_id',
        ),
    ]
