# Generated by Django 5.1.4 on 2025-06-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0043_rename_csc_reg_no_csccenter_csc_id'),
        ('locations', '0029_rename_pincode_uniqueplace_pincodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.uniquedistrict'),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.uniqueplace'),
        ),
        migrations.AlterField(
            model_name='csccenter',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.uniquestate'),
        ),
    ]
