# Generated by Django 5.1.4 on 2025-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0044_alter_csccenter_district_alter_csccenter_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
