# Generated by Django 5.1.4 on 2025-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0045_alter_csccenter_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csccenter',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='csccenter',
            name='pincode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
