# Generated by Django 5.1.4 on 2025-06-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0046_remove_csccenter_zipcode_csccenter_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csccenter',
            name='owner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
