# Generated by Django 5.1.2 on 2024-11-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
