# Generated by Django 5.1.2 on 2024-11-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_testedcoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testedcoordinates',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testedcoordinates',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
