# Generated by Django 5.1.2 on 2024-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
