# Generated by Django 5.1.2 on 2024-11-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_retestedcoordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestedPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
    ]
