# Generated by Django 5.1.2 on 2024-11-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_testedpincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestedPincode',
        ),
    ]
