# Generated by Django 5.1.2 on 2024-12-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_delete_testedpincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
    ]
