# Generated by Django 5.1.4 on 2024-12-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_testpincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='retestedcoordinates',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
