# Generated by Django 5.1.4 on 2025-01-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_uniquedistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquedistrict',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniquestate'),
        ),
    ]
