# Generated by Django 5.1.4 on 2025-01-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_alter_uniquedistrict_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniquePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniquedistrict')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniquestate')),
            ],
            options={
                'db_table': 'unique_places',
                'ordering': ['name'],
            },
        ),
    ]
