# Generated by Django 5.1.4 on 2025-02-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_lekshadweeptestedcoordinates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LekshadweepTestedCoordinates',
            new_name='AndmanAndNicobarTestedCoordinates',
        ),
    ]
