# Generated by Django 5.1.4 on 2025-05-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0024_ksalocationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.PositiveIntegerField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.place')),
            ],
        ),
        migrations.AddField(
            model_name='uniqueplace',
            name='pincode',
            field=models.ManyToManyField(to='locations.placepincode'),
        ),
    ]
