# Generated by Django 5.1.4 on 2025-05-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0025_placepincode_uniqueplace_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepincode',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniqueplace'),
        ),
    ]
