# Generated by Django 5.1.4 on 2025-05-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0026_alter_placepincode_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniqueplace')),
            ],
        ),
    ]
