# Generated by Django 5.1.4 on 2025-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0027_placecoordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueplace',
            name='coordinates',
            field=models.ManyToManyField(to='locations.placecoordinate'),
        ),
    ]
