# Generated by Django 5.1.4 on 2025-05-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0028_uniqueplace_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniqueplace',
            old_name='pincode',
            new_name='pincodes',
        ),
    ]
