# Generated by Django 5.1.4 on 2025-06-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0029_rename_pincode_uniqueplace_pincodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquedistrict',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.uniquestate'),
        ),
    ]
