# Generated by Django 5.1.4 on 2025-06-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0030_alter_uniquedistrict_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueplace',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='locations.uniquedistrict'),
        ),
    ]
