# Generated by Django 5.1.4 on 2025-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0032_pincodeandcoordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincodeandcoordinate',
            name='post_office_id',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
