# Generated by Django 5.1.4 on 2025-06-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0033_pincodeandcoordinate_post_office_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincodeandcoordinate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pincodeandcoordinate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IndiaLocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('address', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.uniqueplace')),
            ],
            options={
                'db_table': 'india_location_data',
                'ordering': ['created'],
            },
        ),
    ]
