# Generated by Django 5.1.4 on 2025-06-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0034_alter_pincodeandcoordinate_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indialocationdata',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.uniqueplace'),
        ),
    ]
