# Generated by Django 5.1.4 on 2025-06-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0035_alter_indialocationdata_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueplace',
            name='alt_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
