# Generated by Django 5.1.4 on 2025-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0037_kuwaitcoordinates_kuwaitlocationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahrainCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BahrainLocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('address', models.CharField(max_length=500)),
                ('requested_latitude', models.FloatField()),
                ('requested_longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Bahrain_location_data',
                'ordering': ['created'],
            },
        ),
    ]
