# Generated by Django 5.1.4 on 2025-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0040_omancoordinates_omanlocationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='IndiaLocationData',
            new_name='IndiaLocationDataOld',
        ),
    ]
