# Generated by Django 5.1.4 on 2025-08-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0041_indiacoordinates_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indialocationdataold',
            table='india_location_data_old',
        ),
    ]
