# Generated by Django 5.1.4 on 2025-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0042_alter_indialocationdataold_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaLocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('address', models.CharField(max_length=500)),
                ('requested_latitude', models.FloatField()),
                ('requested_longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'india_location_data',
                'ordering': ['created'],
            },
        ),
    ]
