# Generated by Django 5.1.4 on 2024-12-30 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educational.program'),
            preserve_default=False,
        ),
    ]
