# Generated by Django 5.1.4 on 2024-12-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0004_specialization_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='lug',
            new_name='slug',
        ),
    ]
