# Generated by Django 5.1.4 on 2024-12-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0005_rename_lug_specialization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
