# Generated by Django 5.1.4 on 2024-12-31 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0008_remove_course_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educational.specialization'),
            preserve_default=False,
        ),
    ]
