# Generated by Django 5.1.4 on 2024-12-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0009_course_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
