# Generated by Django 5.1.4 on 2025-01-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0010_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
