# Generated by Django 5.1.4 on 2025-01-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0011_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
