# Generated by Django 5.1.4 on 2025-01-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0012_remove_course_image'),
        ('locations', '0018_uniqueplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.uniquedistrict'),
        ),
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.uniqueplace'),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.uniquestate'),
        ),
    ]
