# Generated by Django 5.1.4 on 2025-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0014_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
