# Generated by Django 5.1.4 on 2025-01-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0016_verticaltab'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorizontalTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal_title', models.CharField(blank=True, max_length=250, null=True)),
                ('horizontal_headings', models.CharField(blank=True, max_length=250, null=True)),
                ('horizontal_summaries', models.TextField(blank=True, null=True)),
                ('horizontal_bullets', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.course')),
            ],
            options={
                'db_table': 'horizontal_tabs',
                'ordering': ['created'],
            },
        ),
    ]
