# Generated by Django 5.1.4 on 2025-01-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0017_horizontaltab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verticaltab',
            old_name='vertical_headings',
            new_name='vertical_heading',
        ),
        migrations.RenameField(
            model_name='verticaltab',
            old_name='vertical_sub_headings',
            new_name='vertical_sub_heading',
        ),
        migrations.RenameField(
            model_name='verticaltab',
            old_name='vertical_summaries',
            new_name='vertical_summary',
        ),
    ]
