# Generated by Django 5.1.4 on 2025-01-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0020_remove_verticaltab_company_remove_verticaltab_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullets', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vetical_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.verticaltab')),
            ],
            options={
                'db_table': 'vetical_bullets',
                'ordering': ['created'],
            },
        ),
    ]
