# Generated by Django 5.1.4 on 2025-01-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0021_verticalbullet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verticaltab',
            name='vertical_bullets',
        ),
        migrations.AddField(
            model_name='verticaltab',
            name='vertical_bullets',
            field=models.ManyToManyField(to='educational.verticalbullet'),
        ),
    ]
