# Generated by Django 5.1.4 on 2025-01-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0022_remove_verticaltab_vertical_bullets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorizontalBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullets', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('horizontal_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.horizontaltab')),
            ],
            options={
                'db_table': 'horizontal_bullets',
                'ordering': ['created'],
            },
        ),
    ]
