# Generated by Django 5.1.4 on 2025-01-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0023_horizontalbullet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horizontaltab',
            name='horizontal_bullets',
        ),
        migrations.AddField(
            model_name='horizontaltab',
            name='horizontal_bullets',
            field=models.ManyToManyField(to='educational.horizontalbullet'),
        ),
    ]
