# Generated by Django 5.1.4 on 2025-01-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0024_remove_horizontaltab_horizontal_bullets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horizontalbullet',
            name='horizontal_tab',
        ),
        migrations.AddField(
            model_name='horizontalbullet',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horizontalbullet',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educational.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horizontalbullet',
            name='horizontal_headings',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
