# Generated by Django 5.1.4 on 2025-01-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0025_remove_horizontalbullet_horizontal_tab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horizontaltab',
            old_name='horizontal_headings',
            new_name='horizontal_heading',
        ),
        migrations.RenameField(
            model_name='horizontaltab',
            old_name='horizontal_summaries',
            new_name='horizontal_summary',
        ),
    ]
