# Generated by Django 5.1.4 on 2025-01-22 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0026_rename_horizontal_headings_horizontaltab_horizontal_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verticaltab',
            name='course_detail',
        ),
        migrations.AddField(
            model_name='verticaltab',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verticaltab',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educational.course'),
            preserve_default=False,
        ),
    ]
