# Generated by Django 5.1.4 on 2025-01-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0027_remove_verticaltab_course_detail_verticaltab_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verticalbullet',
            old_name='bullets',
            new_name='bullet',
        ),
        migrations.RemoveField(
            model_name='verticalbullet',
            name='vetical_tab',
        ),
        migrations.AddField(
            model_name='verticalbullet',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verticalbullet',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educational.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verticalbullet',
            name='vertical_heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
