# Generated by Django 5.1.4 on 2025-01-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0028_rename_bullets_verticalbullet_bullet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horizontalbullet',
            old_name='bullets',
            new_name='bullet',
        ),
        migrations.RenameField(
            model_name='horizontalbullet',
            old_name='horizontal_headings',
            new_name='horizontal_heading',
        ),
    ]
