# Generated by Django 5.1.4 on 2025-01-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0031_tabledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_title', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.course')),
                ('table_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.tabledata')),
                ('table_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.tableheading')),
            ],
            options={
                'db_table': 'tables',
                'ordering': ['created'],
            },
        ),
    ]
