# Generated by Django 5.1.4 on 2025-01-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0033_tagdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.course')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_of_tag', to='educational.tagdetail')),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['created'],
            },
        ),
    ]
