# Generated by Django 5.1.4 on 2025-01-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0036_timeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='table_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='table_title',
            new_name='title',
        ),
    ]
