# Generated by Django 5.1.4 on 2025-01-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0037_rename_table_data_table_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horizontalbullet',
            old_name='horizontal_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='horizontaltab',
            old_name='horizontal_bullets',
            new_name='bullets',
        ),
        migrations.RenameField(
            model_name='horizontaltab',
            old_name='horizontal_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='horizontaltab',
            old_name='horizontal_summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='horizontaltab',
            old_name='horizontal_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='data',
            new_name='datas',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='heading',
            new_name='headings',
        ),
        migrations.RenameField(
            model_name='tableheading',
            old_name='table_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='verticalbullet',
            old_name='vertical_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='verticaltab',
            old_name='vertical_bullets',
            new_name='bullets',
        ),
        migrations.RenameField(
            model_name='verticaltab',
            old_name='vertical_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='verticaltab',
            old_name='vertical_sub_heading',
            new_name='sub_heading',
        ),
        migrations.RenameField(
            model_name='verticaltab',
            old_name='vertical_summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='verticaltab',
            old_name='vertical_title',
            new_name='title',
        ),
    ]
