# Generated by Django 5.1.4 on 2025-01-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0039_coursedetail_description_coursedetail_summary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDetail',
        ),
    ]
