# Generated by Django 5.1.4 on 2025-01-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0040_delete_coursedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerticalTab',
        ),
    ]
