# Generated by Django 5.1.4 on 2025-01-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0042_delete_horizontaltab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorizontalBullet',
        ),
    ]
