# Generated by Django 5.1.4 on 2025-01-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0044_delete_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableData',
        ),
    ]
