# Generated by Django 5.1.4 on 2025-01-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0045_delete_tabledata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableHeading',
        ),
    ]
