# Generated by Django 5.1.4 on 2025-01-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0046_delete_tableheading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
