# Generated by Django 5.1.4 on 2025-01-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0048_delete_tagdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
