# Generated by Django 5.1.4 on 2025-01-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0049_delete_timeline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimelineDetail',
        ),
    ]
