# Generated by Django 5.1.4 on 2025-01-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0052_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
