# Generated by Django 5.1.4 on 2025-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0054_coursedetail_company_coursedetail_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
