# Generated by Django 5.1.4 on 2025-01-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0056_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='company',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
