# Generated by Django 5.1.4 on 2025-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0059_coursedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='features',
            field=models.ManyToManyField(to='educational.feature'),
        ),
    ]
