# Generated by Django 5.1.4 on 2025-01-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0061_verticalbullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bullets', models.ManyToManyField(to='educational.verticalbullet')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.course')),
            ],
            options={
                'db_table': 'vetical_tabs',
                'ordering': ['created'],
            },
        ),
    ]
