# Generated by Django 5.1.4 on 2025-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0068_coursedetail_horizontal_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('data', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'table_content',
                'ordering': ['created'],
            },
        ),
    ]
