# Generated by Django 5.1.4 on 2025-01-22 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0069_tablecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecontent',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablecontent',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educational.course'),
            preserve_default=False,
        ),
    ]
