# Generated by Django 5.1.4 on 2025-01-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0070_tablecontent_company_tablecontent_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='table_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
