# Generated by Django 5.1.4 on 2025-01-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0071_coursedetail_table_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='table_headings',
            field=models.ManyToManyField(to='educational.tablecontent'),
        ),
    ]
