# Generated by Django 5.1.4 on 2025-01-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description'),
        ('educational', '0072_coursedetail_table_headings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableContent',
            new_name='Table',
        ),
    ]
