# Generated by Django 5.1.4 on 2025-01-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0073_rename_tablecontent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='tag_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
