# Generated by Django 5.1.4 on 2025-01-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0075_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='tags',
            field=models.ManyToManyField(to='educational.tag'),
        ),
    ]
