# Generated by Django 5.1.4 on 2025-01-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0076_coursedetail_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='table_headings',
            new_name='table',
        ),
    ]
