# Generated by Django 5.1.4 on 2025-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0077_rename_table_headings_coursedetail_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='timeline_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
