# Generated by Django 5.1.4 on 2025-01-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0079_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='timelines',
            field=models.ManyToManyField(to='educational.timeline'),
        ),
    ]
