# Generated by Django 5.1.4 on 2025-01-22 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0080_coursedetail_timelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
