# Generated by Django 5.1.4 on 2025-01-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0081_coursedetail_created_coursedetail_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelTable(
            name='coursedetail',
            table='course_details',
        ),
    ]
