# Generated by Django 5.1.4 on 2025-01-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0083_tabledata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
