# Generated by Django 5.1.4 on 2025-01-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0084_alter_table_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='data',
        ),
    ]
