# Generated by Django 5.1.4 on 2025-01-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0085_remove_table_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='datas',
            field=models.ManyToManyField(to='educational.tabledata'),
        ),
    ]
