# Generated by Django 5.1.4 on 2025-01-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0086_table_datas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='table',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.table'),
        ),
    ]
