# Generated by Django 5.1.4 on 2025-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0087_remove_coursedetail_table_coursedetail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='table',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='table',
            field=models.ManyToManyField(to='educational.table'),
        ),
    ]
