# Generated by Django 5.1.4 on 2025-01-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0089_bulletpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='bullet_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
