# Generated by Django 5.1.4 on 2025-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0090_coursedetail_bullet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='bullets',
            field=models.ManyToManyField(to='educational.bulletpoints'),
        ),
    ]
