# Generated by Django 5.1.4 on 2025-01-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0091_coursedetail_bullets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='bullets',
            new_name='bullet_points',
        ),
    ]
