# Generated by Django 5.1.4 on 2025-01-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0092_rename_bullets_coursedetail_bullet_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletpoints',
            old_name='point',
            new_name='bullet_point',
        ),
    ]
