# Generated by Django 5.1.4 on 2025-01-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0093_rename_point_bulletpoints_bullet_point'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verticalbullet',
            table='vertical_bullets',
        ),
        migrations.AlterModelTable(
            name='verticaltab',
            table='vertical_tabs',
        ),
    ]
