# Generated by Django 5.1.4 on 2025-01-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0094_alter_verticalbullet_table_alter_verticaltab_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='horizontal_tab',
            new_name='horizontal_tabs',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='table',
            new_name='tables',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='vertical_tab',
            new_name='vertical_tabs',
        ),
    ]
