# Generated by Django 5.1.4 on 2025-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0095_rename_horizontal_tab_coursedetail_horizontal_tabs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verticalbullet',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
