# Generated by Django 5.1.4 on 2025-02-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0099_enquiry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='district',
        ),
        migrations.RemoveField(
            model_name='course',
            name='place',
        ),
        migrations.RemoveField(
            model_name='course',
            name='state',
        ),
    ]
