# Generated by Django 5.1.4 on 2025-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0101_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='dynamic_place_rendering',
            field=models.BooleanField(default=False),
        ),
    ]
