# Generated by Django 5.1.4 on 2025-02-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0102_faq_dynamic_place_rendering'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_decription',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='meta_tags',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
