# Generated by Django 5.1.4 on 2025-02-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0103_course_meta_decription_course_meta_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='meta_decription',
            new_name='meta_description',
        ),
    ]
