# Generated by Django 5.1.4 on 2025-03-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_delete_multipage'),
        ('educational', '0105_rename_subtitle_course_subtitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vertical_title', models.CharField(blank=True, max_length=250, null=True)),
                ('horizontal_title', models.CharField(blank=True, max_length=250, null=True)),
                ('table_title', models.CharField(blank=True, max_length=250, null=True)),
                ('bullet_title', models.CharField(blank=True, max_length=250, null=True)),
                ('tag_title', models.CharField(blank=True, max_length=250, null=True)),
                ('timeline_title', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bullet_points', models.ManyToManyField(to='educational.bulletpoints')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.course')),
                ('features', models.ManyToManyField(to='educational.feature')),
                ('horizontal_tabs', models.ManyToManyField(to='educational.horizontaltab')),
                ('tables', models.ManyToManyField(to='educational.table')),
                ('tags', models.ManyToManyField(to='educational.tag')),
                ('timelines', models.ManyToManyField(to='educational.timeline')),
                ('vertical_tabs', models.ManyToManyField(to='educational.verticaltab')),
            ],
            options={
                'db_table': 'course_multipages',
                'ordering': ['created'],
            },
        ),
    ]
