# Generated by Django 5.1.4 on 2025-03-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0107_multipagebulletpoints_alter_multipage_bullet_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipagefaq',
            old_name='qusetion',
            new_name='question',
        ),
    ]
