# Generated by Django 5.1.4 on 2025-03-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0108_rename_qusetion_multipagefaq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipagehorizontaltab',
            name='bullets',
            field=models.ManyToManyField(to='educational.multipagehorizontalbullet'),
        ),
        migrations.AlterField(
            model_name='multipageverticaltab',
            name='bullets',
            field=models.ManyToManyField(to='educational.multipageverticalbullet'),
        ),
    ]
