# Generated by Django 5.1.4 on 2025-03-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0109_alter_multipagehorizontaltab_bullets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipagetable',
            name='datas',
            field=models.ManyToManyField(to='educational.multipagetabledata'),
        ),
    ]
