# Generated by Django 5.1.4 on 2025-03-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0110_alter_multipagetable_datas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipagetag',
            name='link',
        ),
    ]
