# Generated by Django 5.1.4 on 2025-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0111_remove_multipagetag_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='meta_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipage',
            name='meta_tags',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
