# Generated by Django 5.1.4 on 2025-03-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0112_multipage_meta_description_multipage_meta_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='hide_bullets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multipage',
            name='hide_faqs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multipage',
            name='hide_horizontal_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multipage',
            name='hide_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multipage',
            name='hide_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multipage',
            name='hide_timeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multipage',
            name='hide_vertical_tab',
            field=models.BooleanField(default=False),
        ),
    ]
