# Generated by Django 5.1.4 on 2025-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0113_multipage_hide_bullets_multipage_hide_faqs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='hide_features',
            field=models.BooleanField(default=False),
        ),
    ]
