# Generated by Django 5.1.4 on 2025-03-22 11:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0115_alter_multipage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='description',
            field=ckeditor.fields.RichTextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='summary',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
