# Generated by Django 5.1.4 on 2025-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0116_alter_coursedetail_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='hide_bullets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='hide_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='hide_horizontal_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='hide_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='hide_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='hide_timeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='hide_vertical_tab',
            field=models.BooleanField(default=False),
        ),
    ]
