# Generated by Django 5.1.4 on 2025-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0117_coursedetail_hide_bullets_coursedetail_hide_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='meta_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='meta_tags',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
