# Generated by Django 5.1.4 on 2025-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0118_coursedetail_meta_description_coursedetail_meta_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='meta_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
