# Generated by Django 5.1.4 on 2025-03-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0119_coursedetail_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='meta_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
