# Generated by Django 5.1.4 on 2025-03-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0121_multipage_url_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='course_tags',
        ),
    ]
