# Generated by Django 5.1.4 on 2025-03-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('educational', '0122_alter_tag_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='meta_tags',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='meta_tags',
            field=models.ManyToManyField(to='base.tag'),
        ),
    ]
