# Generated by Django 5.1.4 on 2025-03-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0123_remove_coursedetail_meta_tags_coursedetail_meta_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDetail',
        ),
    ]
