# Generated by Django 5.1.4 on 2025-03-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tag_metatag_alter_metatag_table'),
        ('educational', '0125_coursedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='meta_tags',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='meta_tags',
            field=models.ManyToManyField(to='base.metatag'),
        ),
    ]
