# Generated by Django 5.1.4 on 2025-03-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0126_remove_coursedetail_meta_tags_coursedetail_meta_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='meta_tags',
        ),
    ]
