# Generated by Django 5.1.4 on 2025-04-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0128_multipage_meta_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='link',
        ),
    ]
