# Generated by Django 5.1.4 on 2025-04-02 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0129_remove_tag_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='vertical_tab_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
