# Generated by Django 5.1.4 on 2025-04-02 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0130_coursedetail_vertical_tab_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='bullet_points_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='horizontal_tab_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='table_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='tags_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='timelines_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
