# Generated by Django 5.1.4 on 2025-04-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0131_coursedetail_bullet_points_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='bullet_points_id',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='horizontal_tab_id',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='table_id',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='tags_id',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='timelines_id',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='vertical_tab_id',
        ),
    ]
