# Generated by Django 5.1.4 on 2025-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0132_remove_coursedetail_bullet_points_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='support_languages',
            field=models.BooleanField(default=True),
        ),
    ]
