# Generated by Django 5.1.4 on 2025-04-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0134_remove_coursedetail_support_languages_and_more'),
        ('locations', '0024_ksalocationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='course_region',
            field=models.CharField(default='All States', max_length=250),
        ),
        migrations.AddField(
            model_name='multipage',
            name='selected_states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.uniquestate'),
        ),
    ]
