# Generated by Django 5.1.4 on 2025-04-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0135_multipage_course_region_multipage_selected_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipage',
            name='course_region',
            field=models.CharField(default='all', max_length=250),
        ),
    ]
