# Generated by Django 5.1.4 on 2025-04-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0136_alter_multipage_course_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='selected_states',
        ),
    ]
