# Generated by Django 5.1.4 on 2025-04-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0137_remove_multipage_selected_states'),
        ('locations', '0024_ksalocationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='available_states',
            field=models.ManyToManyField(to='locations.uniquestate'),
        ),
    ]
