# Generated by Django 5.1.4 on 2025-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0138_multipage_available_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='hide_support_languages',
            field=models.BooleanField(default=False),
        ),
    ]
