# Generated by Django 5.1.4 on 2025-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0140_multipagefaq_slug'),
        ('locations', '0029_rename_pincode_uniqueplace_pincodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagebulletpoints',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagefaq',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagefeature',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontalbullet',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontaltab',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagetable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagetabledata',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagetag',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipagetimeline',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipageverticalbullet',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multipageverticaltab',
            name='course',
        ),
        migrations.AlterField(
            model_name='multipage',
            name='available_states',
            field=models.ManyToManyField(related_name='education_multipage_states', to='locations.uniquestate'),
        ),
    ]
