# Generated by Django 5.1.4 on 2025-05-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0142_multipage_title_multipagebulletpoints_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.course'),
        ),
    ]
