# Generated by Django 5.1.4 on 2025-05-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0143_multipage_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipage',
            name='course',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='educational.course'),
            preserve_default=False,
        ),
    ]
