# Generated by Django 5.1.4 on 2025-07-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0144_alter_multipage_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
    ]
