# Generated by Django 5.1.4 on 2025-07-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0146_multipage_sub_title_alter_multipage_available_states_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='slider_courses',
            field=models.ManyToManyField(to='educational.coursedetail'),
        ),
    ]
