# Generated by Django 5.1.4 on 2025-08-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0149_alter_course_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='tag_title',
        ),
        migrations.DeleteModel(
            name='MultiPageTag',
        ),
    ]
