# Generated by Django 5.1.4 on 2025-08-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0150_remove_multipage_tags_remove_multipage_tag_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='hide_tags',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='tag_title',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='hide_tags',
        ),
    ]
