# Generated by Django 5.1.4 on 2025-08-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0151_remove_coursedetail_hide_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
