# Generated by Django 5.1.4 on 2025-08-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('educational', '0152_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='company.company'),
        ),
    ]
