# Generated by Django 5.1.4 on 2025-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0153_alter_course_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
