# Generated by Django 5.1.2 on 2024-12-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_favicon_alter_company_logo'),
        ('education', '0002_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='company',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
