# Generated by Django 5.1.2 on 2024-10-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companytype_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='companytype',
            table='company_type',
        ),
    ]
