# Generated by Django 5.1.2 on 2024-10-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companytype_options_alter_companytype_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=175, null=True)),
                ('favicon', models.ImageField(upload_to='company_favicon/')),
                ('logo', models.ImageField(upload_to='company_logo/')),
                ('phone1', models.CharField(max_length=50)),
                ('phone2', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companytype')),
            ],
            options={
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
    ]
