# Generated by Django 5.1.2 on 2024-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company_favicon/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
    ]
