# Generated by Django 5.1.4 on 2025-01-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_client_slug_alter_testimonial_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='client_company',
        ),
    ]
