# Generated by Django 5.1.4 on 2025-01-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_testimonial_client_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
