# Generated by Django 5.1.4 on 2025-02-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_delete_testimonial'),
        ('locations', '0018_uniqueplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='student_testimonials/')),
                ('company', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_place', to='locations.uniqueplace')),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['created'],
            },
        ),
    ]
