# Generated by Django 5.1.4 on 2025-02-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_company',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_company', to='company.company'),
        ),
    ]
