# Generated by Django 5.1.4 on 2025-02-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_testimonial_client_company_alter_testimonial_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
