# Generated by Django 5.1.4 on 2025-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_multipage'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='subtitles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
