# Generated by Django 5.1.4 on 2025-03-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_metatag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiPage',
        ),
    ]
