# Generated by Django 5.1.4 on 2025-03-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_delete_multipage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaTag',
        ),
    ]
