# Generated by Django 5.1.4 on 2025-03-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tag_metatag_alter_metatag_table'),
        ('company', '0021_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='meta_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='meta_tags',
            field=models.ManyToManyField(to='base.metatag'),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
