# Generated by Django 5.1.4 on 2025-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_company_facebook_alter_company_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sub_type',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
