# Generated by Django 5.1.4 on 2025-04-22 12:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_company_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='footer_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
