# Generated by Django 5.1.4 on 2025-05-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_company_footer_content'),
        ('locations', '0024_ksalocationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_enquiry_company', to='company.company')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_state', to='locations.uniquestate')),
            ],
            options={
                'db_table': 'contact_enquiries',
                'ordering': ['-created'],
            },
        ),
    ]
