# Generated by Django 5.1.4 on 2025-07-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='add_on_company_types',
            field=models.ManyToManyField(related_name='companies', to='company.companytype'),
        ),
    ]
