# Generated by Django 5.1.4 on 2025-07-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_company_add_on_company_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='add_on_company_types',
            field=models.ManyToManyField(related_name='add_on_companies', to='company.companytype'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.companytype'),
        ),
    ]
