# Generated by Django 5.1.4 on 2025-08-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_alter_company_add_on_company_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='company.company'),
        ),
    ]
