# Generated by Django 5.1.4 on 2025-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_alter_testimonial_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='company',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='company',
            name='youtube',
        ),
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
