# Generated by Django 5.1.4 on 2025-04-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0001_initial'),
        ('locations', '0024_ksalocationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Enquiry_state', to='locations.uniquestate'),
            preserve_default=False,
        ),
    ]
