# Generated by Django 5.1.4 on 2025-06-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0002_enquiry_state'),
        ('locations', '0029_rename_pincode_uniqueplace_pincodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='company_sub_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='locations.uniquestate'),
        ),
    ]
