# Generated by Django 5.1.2 on 2024-11-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_dimensions_product_obj_alter_dimensions_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimensions',
            name='product_obj',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.ManyToManyField(to='product.dimensions'),
        ),
    ]
