# Generated by Django 5.1.2 on 2024-11-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_dimensions_height_remove_dimensions_length_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dimensions',
        ),
    ]
