# Generated by Django 5.1.2 on 2024-11-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delete_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexa',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
