# Generated by Django 5.1.2 on 2024-11-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_color_hexa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
    ]
