# Generated by Django 5.1.4 on 2025-02-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_multipage'),
        ('locations', '0020_rename_lekshadweeptestedcoordinates_andmanandnicobartestedcoordinates'),
        ('product', '0031_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_enquiry_company', to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_enquiry_state', to='locations.uniquestate')),
            ],
            options={
                'db_table': 'product_enquiries',
                'ordering': ['-created'],
            },
        ),
    ]
