# Generated by Django 5.1.4 on 2025-03-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_multipagebulletpoint_multipagefaq_multipagefeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipage',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
