# Generated by Django 5.1.4 on 2025-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_bulletpoint_feature_horizontalbullet_horizontaltab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
