# Generated by Django 5.1.4 on 2025-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_productdetailpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='meta_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
