# Generated by Django 5.1.4 on 2025-03-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_multipage_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='url_type',
            field=models.CharField(default='slug_filtered', max_length=50),
        ),
    ]
