# Generated by Django 5.1.4 on 2025-03-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_multipage_url_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='buy_now_action',
            field=models.CharField(default='whatsapp', max_length=50),
        ),
        migrations.AddField(
            model_name='multipage',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='multipage',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='buy_now_action',
            field=models.CharField(default='whatsapp', max_length=50),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
