# Generated by Django 5.1.4 on 2025-03-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_multipage_buy_now_action_multipage_external_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipage',
            old_name='whatsapp_number',
            new_name='whatsapp',
        ),
        migrations.RenameField(
            model_name='productdetailpage',
            old_name='whatsapp_number',
            new_name='whatsapp',
        ),
    ]
