# Generated by Django 5.1.4 on 2025-03-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_rename_whatsapp_number_multipage_whatsapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailpage',
            name='meta_tags',
        ),
    ]
