# Generated by Django 5.1.4 on 2025-05-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_remove_horizontaltab_bullets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailpage',
            name='bullet_title',
        ),
    ]
