# Generated by Django 5.1.4 on 2025-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_remove_productdetailpage_bullet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='hide_support_languages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='hide_support_languages',
            field=models.BooleanField(default=False),
        ),
    ]
