# Generated by Django 5.1.4 on 2025-05-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='product',
        ),
    ]
