# Generated by Django 5.1.4 on 2025-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_remove_multipage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='products',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
