# Generated by Django 5.1.4 on 2025-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_multipage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
