# Generated by Django 5.1.4 on 2025-05-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_multipage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipagebulletpoint',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipagefaq',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipagefeature',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontalbullet',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontaltab',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipagetable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipagetabledata',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipagetag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipagetimeline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipageverticalbullet',
            name='product',
        ),
        migrations.RemoveField(
            model_name='multipageverticaltab',
            name='product',
        ),
    ]
