# Generated by Django 5.1.4 on 2025-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_remove_multipagebulletpoint_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipagebulletpoint',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagefaq',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagefeature',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagehorizontalbullet',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagehorizontaltab',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagetable',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagetabledata',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagetag',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipagetimeline',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipageverticalbullet',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipageverticaltab',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
