# Generated by Django 5.1.4 on 2025-05-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_multipagebulletpoint_title_multipagefaq_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipagehorizontaltab',
            name='bullets',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontaltab',
            name='company',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='horizontal_tabs',
        ),
        migrations.RemoveField(
            model_name='multipagetable',
            name='company',
        ),
        migrations.RemoveField(
            model_name='multipagetable',
            name='datas',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='multipagetabledata',
            name='company',
        ),
        migrations.RemoveField(
            model_name='multipageverticalbullet',
            name='company',
        ),
        migrations.RemoveField(
            model_name='multipageverticaltab',
            name='bullets',
        ),
        migrations.RemoveField(
            model_name='multipageverticaltab',
            name='company',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='vertical_tabs',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='horizontal_title',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='table_title',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='vertical_title',
        ),
        migrations.DeleteModel(
            name='MultiPageHorizontalBullet',
        ),
        migrations.DeleteModel(
            name='MultiPageHorizontalTab',
        ),
        migrations.DeleteModel(
            name='MultiPageTable',
        ),
        migrations.DeleteModel(
            name='MultiPageTableData',
        ),
        migrations.DeleteModel(
            name='MultiPageVerticalBullet',
        ),
        migrations.DeleteModel(
            name='MultiPageVerticalTab',
        ),
    ]
