# Generated by Django 5.1.4 on 2025-05-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_remove_multipagehorizontaltab_bullets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='hide_horizontal_tab',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='hide_table',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='hide_vertical_tab',
        ),
    ]
