# Generated by Django 5.1.4 on 2025-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0029_rename_pincode_uniqueplace_pincodes'),
        ('product', '0057_remove_multipage_hide_horizontal_tab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='available_states',
            field=models.ManyToManyField(related_name='product_multipage_states', to='locations.uniquestate'),
        ),
        migrations.AddField(
            model_name='multipage',
            name='product_region',
            field=models.CharField(default='all', max_length=250),
        ),
    ]
