# Generated by Django 5.1.4 on 2025-07-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_multipage_available_states_multipage_product_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
    ]
