# Generated by Django 5.1.4 on 2025-07-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_banner'),
        ('locations', '0040_omancoordinates_omanlocationdata'),
        ('product', '0059_remove_enquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='available_states',
            field=models.ManyToManyField(related_name='product_multipages', to='locations.uniquestate'),
        ),
        migrations.AlterField(
            model_name='multipage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_multipages', to='company.company'),
        ),
    ]
