# Generated by Django 5.1.4 on 2025-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_multipage_sub_title_alter_multipage_available_states_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipagefaq',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
