# Generated by Django 5.1.4 on 2025-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_multipagefaq_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
