# Generated by Django 5.1.4 on 2025-08-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_alter_color_hexa_alter_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='home_footer_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
