# Generated by Django 5.1.4 on 2025-08-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdetailpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='hide_tags',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='tag_title',
        ),
        migrations.RemoveField(
            model_name='productdetailpage',
            name='hide_tags',
        ),
        migrations.RemoveField(
            model_name='productdetailpage',
            name='tag_title',
        ),
        migrations.DeleteModel(
            name='MultiPageTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
