# Generated by Django 5.1.4 on 2025-08-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('product', '0066_remove_multipage_tags_remove_tag_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company'),
        ),
    ]
