# Generated by Django 5.1.4 on 2025-02-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('registration', '0007_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='registration_type',
        ),
        migrations.AddField(
            model_name='blog',
            name='registration_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubtype'),
        ),
    ]
