# Generated by Django 5.1.4 on 2025-02-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='type',
            new_name='company_type',
        ),
    ]
