# Generated by Django 5.1.4 on 2025-02-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_type_blog_company_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='company_type',
            new_name='blog_type',
        ),
    ]
