# Generated by Django 5.1.4 on 2025-03-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_company_type_blog_blog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='meta_tags',
        ),
    ]
