# Generated by Django 5.1.4 on 2025-03-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tag_metatag_alter_metatag_table'),
        ('blog', '0007_remove_blog_meta_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_tags',
            field=models.ManyToManyField(to='base.metatag'),
        ),
    ]
