# Generated by Django 5.1.4 on 2025-08-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_content'),
        ('registration', '0033_alter_registrationsubtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='registration_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_blogs', to='registration.registrationsubtype'),
        ),
    ]
