# Generated by Django 5.1.4 on 2025-08-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_registration_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='registration_sub_type',
        ),
    ]
