# Generated by Django 5.1.4 on 2025-08-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_registration_sub_type'),
        ('registration', '0052_multipage_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='registration.registration'),
        ),
    ]
