# Generated by Django 5.1.4 on 2025-04-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='BZ India', max_length=250)),
                ('content', models.TextField(default='BZ India is a joint venture group that partners with leading companies across diverse sectors to deliver top-tier services in the Indian market')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'home_main_content',
            },
        ),
    ]
