# Generated by Django 5.1.4 on 2025-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='meta_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincontent',
            name='meta_title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
