# Generated by Django 5.1.4 on 2025-04-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_maincontent_meta_description_maincontent_meta_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincontent',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='maincontent',
            old_name='heading',
            new_name='title',
        ),
    ]
