# Generated by Django 5.1.4 on 2025-04-15 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_content_maincontent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontent',
            name='description',
            field=ckeditor.fields.RichTextField(default='BZ India is a joint venture group that partners with leading companies across diverse sectors to deliver top-tier services in the Indian market'),
        ),
    ]
