# Generated by Django 5.1.4 on 2025-04-15 14:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_maincontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='footer_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
