# Generated by Django 5.1.4 on 2025-04-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_maincontent_footer_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainContent',
            new_name='HomeContent',
        ),
    ]
