# Generated by Django 5.1.4 on 2025-07-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
