# Generated by Django 5.1.4 on 2025-02-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='name',
            field=models.CharField(default='Meenakshi Nambiar', max_length=250),
            preserve_default=False,
        ),
    ]
