# Generated by Django 5.1.4 on 2025-02-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_enquiry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
