# Generated by Django 5.1.4 on 2025-02-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
