# Generated by Django 5.1.4 on 2025-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='dynamic_place_rendering',
            field=models.BooleanField(default=False),
        ),
    ]
