# Generated by Django 5.1.4 on 2025-03-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_metatag'),
        ('service', '0015_horizontalbullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorizontalTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bullets', models.ManyToManyField(to='service.horizontalbullet')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_horizontal_tab_company', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_horizontal_tabs',
                'ordering': ['created'],
            },
        ),
    ]
