# Generated by Django 5.1.4 on 2025-03-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_metatag'),
        ('service', '0021_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vertical_title', models.CharField(blank=True, max_length=250, null=True)),
                ('horizontal_title', models.CharField(blank=True, max_length=250, null=True)),
                ('table_title', models.CharField(blank=True, max_length=250, null=True)),
                ('bullet_title', models.CharField(blank=True, max_length=250, null=True)),
                ('tag_title', models.CharField(blank=True, max_length=250, null=True)),
                ('timeline_title', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bullet_points', models.ManyToManyField(to='service.bulletpoints')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('features', models.ManyToManyField(to='service.feature')),
                ('horizontal_tabs', models.ManyToManyField(to='service.horizontaltab')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('tables', models.ManyToManyField(to='service.table')),
                ('tags', models.ManyToManyField(to='service.tag')),
                ('timelines', models.ManyToManyField(to='service.timeline')),
                ('vertical_tabs', models.ManyToManyField(to='service.verticaltab')),
            ],
            options={
                'db_table': 'service_details',
                'ordering': ['created'],
            },
        ),
    ]
