# Generated by Django 5.1.4 on 2025-03-22 14:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_delete_multipage'),
        ('service', '0022_servicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPageBulletPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_point', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_bullets', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_bullet_points',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_faq', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_faqs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_feature', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_features',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageHorizontalBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('bullet', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_horizontal_bullet', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_horizontal_bullets',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageHorizontalTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bullets', models.ManyToManyField(to='service.multipagehorizontalbullet')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_horizontal_tab', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_horizontal_tabs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('data', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_table_data', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_table_data',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_table', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('datas', models.ManyToManyField(to='service.multipagetabledata')),
            ],
            options={
                'db_table': 'service_multipage_table',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_tag', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_tags',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_timeline', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_timelines',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageVerticalBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True)),
                ('bullet', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_vertical_bullet', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_vertical_bullets',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPageVerticalTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bullets', models.ManyToManyField(to='service.multipageverticalbullet')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage_vertical_tab', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'service_multipage_vertical_tabs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MultiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('meta_tags', models.CharField(max_length=250)),
                ('meta_description', models.TextField()),
                ('vertical_title', models.CharField(blank=True, max_length=250, null=True)),
                ('horizontal_title', models.CharField(blank=True, max_length=250, null=True)),
                ('table_title', models.CharField(blank=True, max_length=250, null=True)),
                ('bullet_title', models.CharField(blank=True, max_length=250, null=True)),
                ('tag_title', models.CharField(blank=True, max_length=250, null=True)),
                ('timeline_title', models.CharField(blank=True, max_length=250, null=True)),
                ('hide_features', models.BooleanField(default=False)),
                ('hide_vertical_tab', models.BooleanField(default=False)),
                ('hide_horizontal_tab', models.BooleanField(default=False)),
                ('hide_table', models.BooleanField(default=False)),
                ('hide_bullets', models.BooleanField(default=False)),
                ('hide_tags', models.BooleanField(default=False)),
                ('hide_timeline', models.BooleanField(default=False)),
                ('hide_faqs', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_of_service_multipage', to='company.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('bullet_points', models.ManyToManyField(to='service.multipagebulletpoints')),
                ('faqs', models.ManyToManyField(to='service.multipagefaq')),
                ('features', models.ManyToManyField(to='service.multipagefeature')),
                ('horizontal_tabs', models.ManyToManyField(to='service.multipagehorizontaltab')),
                ('tables', models.ManyToManyField(to='service.multipagetable')),
                ('tags', models.ManyToManyField(to='service.multipagetag')),
                ('timelines', models.ManyToManyField(to='service.multipagetimeline')),
                ('vertical_tabs', models.ManyToManyField(to='service.multipageverticaltab')),
            ],
            options={
                'db_table': 'service_multipages',
                'ordering': ['created'],
            },
        ),
    ]
