# Generated by Django 5.1.4 on 2025-03-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_delete_multipage'),
        ('service', '0023_multipagebulletpoints_multipagefaq_multipagefeature_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiPageBulletPoints',
            new_name='MultiPageBulletPoint',
        ),
    ]
