# Generated by Django 5.1.4 on 2025-03-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_rename_multipagebulletpoints_multipagebulletpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='hide_bullets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='hide_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='hide_horizontal_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='hide_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='hide_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='hide_timeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='hide_vertical_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='meta_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='meta_tags',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
