# Generated by Django 5.1.4 on 2025-03-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_servicedetail_hide_bullets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='meta_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
