# Generated by Django 5.1.4 on 2025-03-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tag_metatag_alter_metatag_table'),
        ('service', '0029_remove_multipage_meta_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='meta_tags',
            field=models.ManyToManyField(related_name='meta_tags_of_multi_page', to='base.metatag'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='meta_tags',
            field=models.ManyToManyField(related_name='meta_tags_of_detail_page', to='base.metatag'),
        ),
    ]
