# Generated by Django 5.1.4 on 2025-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_multipage_meta_tags_servicedetail_meta_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='hide_support_languages',
            field=models.BooleanField(default=False),
        ),
    ]
