# Generated by Django 5.1.4 on 2025-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0029_rename_pincode_uniqueplace_pincodes'),
        ('service', '0031_servicedetail_hide_support_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='available_states',
            field=models.ManyToManyField(related_name='service_multipage_available_states', to='locations.uniquestate'),
        ),
        migrations.AddField(
            model_name='multipage',
            name='hide_support_languages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multipage',
            name='service_region',
            field=models.CharField(default='all', max_length=250),
        ),
    ]
