# Generated by Django 5.1.4 on 2025-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_multipage_available_states_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
