# Generated by Django 5.1.4 on 2025-06-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_multipage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipagebulletpoint',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipagefaq',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipagefeature',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontalbullet',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipagehorizontaltab',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipagetable',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipagetabledata',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipagetag',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipagetimeline',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipageverticalbullet',
            name='service',
        ),
        migrations.RemoveField(
            model_name='multipageverticaltab',
            name='service',
        ),
    ]
