# Generated by Django 5.1.4 on 2025-07-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_multipagebulletpoint_title_multipagefaq_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
    ]
