# Generated by Django 5.1.4 on 2025-07-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_banner'),
        ('service', '0037_multipage_sub_title_alter_multipage_available_states_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipagefaq',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multipagefaq',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_faqs', to='company.company'),
        ),
    ]
