# Generated by Django 5.1.4 on 2025-07-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0039_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipage',
            name='slider_services',
            field=models.ManyToManyField(to='service.servicedetail'),
        ),
    ]
