# Generated by Django 5.1.4 on 2025-08-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0040_multipage_slider_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='home_footer_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
