# Generated by Django 5.1.4 on 2025-08-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0041_servicedetail_home_footer_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='home_footer_visibility',
        ),
        migrations.AddField(
            model_name='multipage',
            name='home_footer_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
