# Generated by Django 5.1.4 on 2025-08-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0044_alter_service_category_alter_service_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='hide_tags',
        ),
        migrations.RemoveField(
            model_name='multipage',
            name='tag_title',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='hide_tags',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='meta_tags',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='tag_title',
        ),
        migrations.DeleteModel(
            name='MultiPageTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
