# Generated by Django 5.1.4 on 2025-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_metatag_meta_description_metatag_meta_title'),
        ('service', '0045_remove_multipage_tags_remove_tag_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='meta_tags',
            field=models.ManyToManyField(related_name='meta_tags_of_detail_page', to='base.metatag'),
        ),
    ]
