# Generated by Django 5.1.4 on 2025-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0047_alter_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
