# Generated by Django 5.1.4 on 2025-08-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0050_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='summary',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
