# Generated by Django 5.1.4 on 2025-08-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0051_alter_servicedetail_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
