# Generated by Django 5.1.4 on 2025-08-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_remove_company_facebook_remove_company_linkedin_and_more'),
        ('service', '0053_alter_multipage_slug_alter_servicedetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='company.company'),
        ),
    ]
