# Generated by Django 5.1.4 on 2025-03-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tag_slug'),
        ('educational', '0123_remove_coursedetail_meta_tags_coursedetail_meta_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='MetaTag',
        ),
        migrations.AlterModelTable(
            name='metatag',
            table='meta_tags',
        ),
    ]
