# Generated by Django 5.1.4 on 2025-04-03 11:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tag_metatag_alter_metatag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatag',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
