# Generated by Django 5.1.4 on 2025-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_metatag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
