# Generated by Django 5.1.4 on 2025-04-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_metatag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatag',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metatag',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
